name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target:
        - x86_64-unknown-linux-gnu
        - i686-unknown-linux-gnu
        - aarch64-unknown-linux-gnu
        - x86_64-apple-darwin
        - x86_64-pc-windows-msvc
        include:
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-22.04
        - target: i686-unknown-linux-gnu
          os: ubuntu-22.04
        - target: aarch64-unknown-linux-gnu
          os: ubuntu-22.04
        - target: x86_64-apple-darwin
          os: macos-latest
        - target: x86_64-pc-windows-msvc
          os: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        target: ${{ matrix.target }}
    - name: Install GCC (i686-unknown-linux-gnu)
      if: ${{ matrix.target == 'i686-unknown-linux-gnu' }}
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends gcc-multilib g++-multilib
      shell: bash
    - name: Install GCC (aarch64-unknown-linux-gnu)
      if: ${{ matrix.target == 'aarch64-unknown-linux-gnu' }}
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross
      shell: bash
    - name: Build
      run: |
        cargo build --manifest-path testcrate/Cargo.toml --target ${{ matrix.target }} --release
      shell: bash

  cross-compile:
    name: Cross-compilation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
        - thumbv6m-none-eabi
        - thumbv7m-none-eabi
        - thumbv7em-none-eabi
        - thumbv7em-none-eabihf
        - thumbv8m.main-none-eabi
        - thumbv8m.main-none-eabihf
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        target: ${{ matrix.target }}
        components: rust-src
    - name: Install Arm GCC (${{ matrix.target }})
      if: startsWith(matrix.target, 'thumbv')
      uses: ryanwinter/arm-none-eabi-gcc@master
      with:
        release: '10.3-2021.10'
    - name: Build Luau
      run: |
        cargo build --manifest-path testcrate/Cargo.toml --target ${{ matrix.target }} --release --no-default-features
      shell: bash

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        include:
        - os: ubuntu-22.04
          target: x86_64-unknown-linux-gnu
        - os: macos-latest
          target: x86_64-apple-darwin
        - os: windows-latest
          target: x86_64-pc-windows-msvc
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        target: ${{ matrix.target }}
    - name: Run tests
      run: |
        cargo test --manifest-path testcrate/Cargo.toml --release
      shell: bash

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - run: cargo fmt -- --check
